WHEN V_NUMBER=0 THEN
V_RESULT:='NUMBER is zero';

WHEN V_NUMBER=1 THEN;
V_RESULT:='NUMBER is one';

WHEN V_NUMBER=2 THEN;
V_RESULT:='NUMBER is two';

WHEN V_NUMBER=3 THEN;
V_RESULT:='NUMBER is three';

ELSE
V_RESULT:='NUMBER is greater than three';

END CASE;
DBMS_OUTPUT.PUT_LINE('CASE Example');
DBMS_OUTPUT.PUT_LINE(V_RESULT);
END;